### PR TITLE
Update compound mapping and connector

### PR DESCRIPTION
**Pull request by thrilok209**
To update InstaConnectorsV2 address in compound mapping contract. And Redeploy `COMPOUND-A` connector.

### CODE REVIEW

**Comment by thrilok209** [comment]
### Deployed connector:

**Connector Name**: "COMPOUND-A"
**Connector Address**: [0x1B1EACaa31abbE544117073f6F8F658a56A3aE25](https://etherscan.io/address/0x1B1EACaa31abbE544117073f6F8F658a56A3aE25)

### Deployed Compound mapping:
**InstaCompoundMapping**: [0xe7a85d0adDB972A4f0A4e57B698B37f171519e88](https://etherscan.io/address/0xe7a85d0adDB972A4f0A4e57B698B37f171519e88)

**Review by KaymasJain — APPROVED** [review]

**Comment by thrilok209** [comment]
Updating Compound connector transaction has been scheduled: https://etherscan.io/tx/0x78b8f7a846a6ee8e379568ddae260a401d3034dc099fd5b23b8965cc1f040f94

It should be executable after Sat Aug 07 2021 18:45:27 GMT+0000.

**Comment by thrilok209** [comment]
Compound connector updated: https://etherscan.io/tx/0xec401cd3f316574711eb4118a4cdd5098bca10f7993b35b308781dad2aa669c2

**Comment by thrilok209** [comment]
### Deployed connector:

____

**Connector Name**: "REFINANCE-A"
**Connector Address**: [0x6f22931423e8ffC8d51f6E5aF73118fC64b27856](https://etherscan.io/address/0x6f22931423e8ffC8d51f6E5aF73118fC64b27856)

---

**Connector Name**: "COMP-A"
**Connector Address**: [0x907F0C8c99B08606eE0A51ec5Bc3dFdbFC2d92f3](https://etherscan.io/address/0x907F0C8c99B08606eE0A51ec5Bc3dFdbFC2d92f3)

**Comment by thrilok209** [comment]
Updated Refinance and COMP connector: https://etherscan.io/tx/0x9eec4a560a408276151c5524bdc7f7980e76c7532da4133e5c945325a67cc8b3

**Pull request merged**
