### PR TITLE
raw function added

### PR DESCRIPTION
**Pull request by KaymasJain**
Adding raw functions to Compound & Aave so developers/users can use them even when we don't have the updated mapping. In raw functions developer will pass the ctoken address, etc from the frontend.

### CODE REVIEW

**Comment by KaymasJain** [comment]
In Compound the liquidation function is remaining

**Comment by thrilok209** [comment]
@KaymasJain Should we remove the liquidation function? We are not using it anywhere maybe we can create another connector for this function?

@mubaris Could you add comments for the extra functions?

**Comment by KaymasJain** [comment]
I think let's keep it. If in future some developer would want to use it.

**Comment by KaymasJain** [comment]
@mubaris I discussed with @thrilok209 and I think we can go without adding any mapping on Aave as it has internal mapping.

If things look good we can merge this branch. Also, check the events properly once :)

**Comment by mubaris** [comment]
LGTM.

Added a raw method for `liquidate` as well

**Review by mubaris — APPROVED** [review]

**Comment by KaymasJain** [comment]
LGTM

@thrilok209 you can merge it if everything looks good to you :)

**Review by thrilok209 — APPROVED** [review]

**Pull request merged**
