### PR TITLE
Workflow update

### PR DESCRIPTION
**Pull request by Ardhead**

### CODE REVIEW

**Comment by ishanjain28** [comment]
We also do not need to include pre-compiled checks in the repository. `ts-node status-checks` in #181 appears to be working okay. 

So, I believe this PR is not needed.

**Comment by Ardhead** [comment]
> We also do not need to include pre-compiled checks in the repository. `ts-node status-checks` in #181 appears to be working okay.
> 
> So, I believe this PR is not needed.

https://github.com/Instadapp/dsa-connectors/runs/5410711265?check_suite_focus=true
Not working...

**Comment by Ardhead** [comment]
> We also do not need to include pre-compiled checks in the repository. `ts-node status-checks` in #181 appears to be working okay.
> 
> So, I believe this PR is not needed.

@ishanjain28 
https://github.com/Instadapp/dsa-connectors/runs/5410711265?check_suite_focus=true
Not working...

**Comment by Ardhead** [comment]
> All checks have failed
> 1 failing check

**Comment by ishanjain28** [comment]
@Ardhead Working on it

**Comment by Ardhead** [comment]
> @Ardhead Working on it

ts-node status-checks working for local run. But not in action

**Comment by ishanjain28** [comment]
@Ardhead Since it's calling that from bash, It needs to call, `npx ts-node`. `$NPM_PREFIX/.bin` is not included in the `$PATH` when called this way so it can't find `ts-node` script.

**Pull request closed without merging**
