### PR TITLE
Added SPDX License 

### PR DESCRIPTION
**Pull request by bhavik-m**
Added SPDX License on all solidity files

### CODE REVIEW

**Review by pradyuman-verma — APPROVED** [review]

**Review by pradyuman-verma — APPROVED** [review]

**Comment by pradyuman-verma** [comment]
@thrilok209 Do we also add SPDX-LICENSE to` connector_old` files?

**Comment by thrilok209** [comment]
> @thrilok209 Do we also add SPDX-LICENSE to` connector_old` files?

@pradyuman-verma @bhavik-m Let's remove `connector_old` folder. So, we can clean up things. We are not using it anywhere as of now. Let's do that in another pr

**Comment by pradyuman-verma** [comment]
> @pradyuman-verma @bhavik-m Let's remove connector_old folder. So, we can clean up things. We are not using it anywhere as of now. Let's do that in another pr

Alright @thrilok209 , then merging this

**Comment by bhavik-m** [comment]
> > @thrilok209 Do we also add SPDX-LICENSE to` connector_old` files?
> 
> @pradyuman-verma @bhavik-m Let's remove `connector_old` folder. So, we can clean up things. We are not using it anywhere as of now. Let's do that in another pr

Okay.

**Comment by bhavik-m** [comment]
@thrilok209 Should i also delete the deprecated connectors?

**Comment by thrilok209** [comment]
> @thrilok209 Should i also delete the deprecated connectors?
> 

Like? Can you list few over here?

**Comment by bhavik-m** [comment]
> > @thrilok209 Should i also delete the deprecated connectors?
> 
> Like? Can you list few over here?

Basically this folder : https://github.com/Instadapp/dsa-connectors/tree/main/contracts/mainnet/deprecated

**Pull request merged**
